### ISSUE TITLE
demo不能直接运行

### ISSUE THREAD

**Issue by zhongcaiwei** [maptalks/maptalks.biglayer#23]
1、demo里面好多案例对应js文件找不到；
2、文件的命名也有点怪怪的，maptalks.webgl.js与maptalks.biglayer.js，dist文件里面命名为maptalks.biglayer.js，调用的文件里面又是maptalks.webgl.js

**Comment by fuzhenn** [comment]
这个插件以前叫maptalks.webgl，后来改名成了maptalks.biglayer。因为还没正式发布，所以demo乱一点。
等发布以后我会都整理好的(这几天暂时没时间)
